INSERT INTO musics (name, artist, year) VALUES
	("Smells Like Teen Spirit", "Nirvana", 1991),
	("Wannabe", "Spice Girls", 1996),
	("November Rain", "Guns N' Roses", 1991),
	("I Want You Back", "N'Sync", 1996),
	("Malandragem", "Cássia Eller", 1994),
	("Say You'll Be There", "Spice Girls", 1996),
	("Come As You Are", "Nirvana", 1991),
	("Don't Cry", "Guns N' Roses", 1991),
	("Tearin' Up My Heart", "N'Sync", 1997),
	("Por Enquanto", "Cássia Eller", 1990),
	("O Segundo Sol", "Cássia Eller", 1999),
	("Spice Up Your Life", "Spice Girls", 1997),
	("Lithium", "Nirvana", 1991),
	("Viva Forever", "Spice Girls", 1998),
	("I Want It That Way", "Backstreet Boys", 1999),
	("2 Become 1", "Spice Girls", 1996),
	("Yesterdays", "Guns N' Roses", 1991),
	("Heart-Shaped Box", "Nirvana", 1993),
	("Na Rua, na Chuva, na Fazenda", "Kid Abelha", 1996),
	("Stop", "Spice Girls", 1998);